# Generated by Django 6.0.3 on 2026-04-26 20:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comentario_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='created_at',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
