# Generated by Django 6.0.3 on 2026-04-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_comentario_created_at_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
