# Generated by Django 6.0.3 on 2026-04-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('servico', 'Serviços'), ('venda', 'Vendas'), ('doacao', 'Doações & Desapego'), ('aviso', 'Avisos'), ('achados', 'Achados e Perdidos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
