# Generated by Django 6.0.3 on 2026-08-10 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_alter_post_categoria_alter_post_telefone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comentario",
            options={"ordering": ["data_criacao"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.AddConstraint(
            model_name="curtida",
            constraint=models.UniqueConstraint(
                fields=("usuario", "post"), name="curtida_unica_por_usuario_e_post"
            ),
        ),
    ]
