# Generated by Django 6.0.3 on 2026-09-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_alter_comentario_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="origem",
            field=models.CharField(
                choices=[
                    ("site", "Formulário do site"),
                    ("mensagem", "Mensagem recebida"),
                ],
                default="site",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("rascunho", "Rascunho"), ("publicado", "Publicado")],
                default="publicado",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MensagemRecebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("teste", "Teste"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remetente", models.CharField(max_length=64)),
                ("texto", models.TextField()),
                ("id_externo", models.CharField(blank=True, max_length=128)),
                ("recebida_em", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processada", "Processada"),
                            ("descartada", "Descartada"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=12,
                    ),
                ),
                ("erro", models.TextField(blank=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensagens",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem recebida",
                "verbose_name_plural": "mensagens recebidas",
                "ordering": ["-recebida_em"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("id_externo", ""), _negated=True),
                        fields=("canal", "id_externo"),
                        name="mensagem_unica_por_canal_e_id_externo",
                    )
                ],
            },
        ),
    ]
